doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 300
uses:
  - django
  - celery
  - flask
autodetect: true
requirements:
  - deps/core.txt
  - deps/test.txt
ignore-paths:
  - docs
  - mypackage/vendor
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 2
